# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_web_app', '0003_auto_20160806_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='autotask_password',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='autotask_username',
            field=models.CharField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
