# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_web_app', '0005_bookingindetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingindetails',
            name='user',
        ),
        migrations.AddField(
            model_name='bookingindetails',
            name='profile_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autotask_web_app.Profile'),
            preserve_default=False,
        ),
    ]
