# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_web_app', '0006_auto_20160807_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingindetails',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
