# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_web_app', '0007_auto_20160807_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upsell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=254)),
                ('account_id', models.CharField(max_length=254)),
                ('product_price', models.FloatField()),
                ('product_cost', models.FloatField()),
                ('product_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='bookingindetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upsell',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autotask_web_app.Profile'),
        ),
    ]
