# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_web_app', '0008_auto_20160808_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='upsell',
            name='opportunity_id',
            field=models.CharField(default=29736286, max_length=254),
            preserve_default=False,
        ),
    ]
