# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_web_app', '0012_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='entity',
            field=models.CharField(default='Ticket', max_length=254),
            preserve_default=False,
        ),
    ]
