# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_web_app', '0013_validation_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='picklist_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
