# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_web_app', '0014_validation_picklist_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autotask_web_app.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='validation',
            name='validation_rule',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='autotask_web_app.ValidationRule'),
            preserve_default=False,
        ),
    ]
