# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_web_app', '0016_auto_20160812_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrule',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autotask_web_app.Entity'),
            preserve_default=False,
        ),
    ]
