# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_web_app', '0017_validationrule_entity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValidationRule',
            new_name='ValidationGroup',
        ),
        migrations.RenameField(
            model_name='validation',
            old_name='validation_rule',
            new_name='validation_group',
        ),
    ]
